[{"Timestamp":"2023-03-02T23:41:46.055505183Z","app.now":"2023-03-02T23:41:46.055521+00:00","duration_ms":0.08055,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":0,"span.num_links":0,"status_code":0,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"c3ba21bf37460e48","trace.span_id":"a997bf3888000784","trace.trace_id":"24b156b63d8714ff6caf6626be494b1e","type":"internal"},{"Timestamp":"2023-03-02T23:41:46.054814803Z","duration_ms":1.62736,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.status_code":200,"http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":39844,"service.name":"backend-flask","span.kind":"server","span.num_events":0,"span.num_links":0,"status_code":0,"telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"c3ba21bf37460e48","trace.trace_id":"24b156b63d8714ff6caf6626be494b1e","type":"server"},{"Timestamp":"2023-03-02T23:41:45.172567118Z","app.now":"2023-03-02T23:41:45.172586+00:00","duration_ms":0.09627,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":0,"span.num_links":0,"status_code":0,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"e4da3461accb7965","trace.span_id":"f27580a294c2ef66","trace.trace_id":"7d1190cbada32981113f6afd31f678df","type":"internal"},{"Timestamp":"2023-03-02T23:41:45.168283588Z","duration_ms":5.40333,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.status_code":200,"http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":39838,"service.name":"backend-flask","span.kind":"server","span.num_events":0,"span.num_links":0,"status_code":0,"telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"e4da3461accb7965","trace.trace_id":"7d1190cbada32981113f6afd31f678df","type":"server"},{"Timestamp":"2023-03-02T23:40:43.023973432Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"926b983ed5e123d1","trace.trace_id":"d9901c44eedaeb001236e4fba019cade"},{"Timestamp":"2023-03-02T23:40:43.023471442Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"e9c0fb32a636b443","trace.trace_id":"d9901c44eedaeb001236e4fba019cade"},{"Timestamp":"2023-03-02T23:40:43.023242882Z","duration_ms":0.24565,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"926b983ed5e123d1","trace.span_id":"e9c0fb32a636b443","trace.trace_id":"d9901c44eedaeb001236e4fba019cade","type":"internal"},{"Timestamp":"2023-03-02T23:40:43.022589242Z","duration_ms":1.396,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":39156,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"926b983ed5e123d1","trace.trace_id":"d9901c44eedaeb001236e4fba019cade","type":"server"},{"Timestamp":"2023-03-02T23:40:41.633179694Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"cf1940eaa36baee6","trace.trace_id":"62032b8bcdc8dbbc66efa93c42e9a80d"},{"Timestamp":"2023-03-02T23:40:41.632680644Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"1f8a359787ce125b","trace.trace_id":"62032b8bcdc8dbbc66efa93c42e9a80d"},{"Timestamp":"2023-03-02T23:40:41.632446224Z","duration_ms":0.25138,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"cf1940eaa36baee6","trace.span_id":"1f8a359787ce125b","trace.trace_id":"62032b8bcdc8dbbc66efa93c42e9a80d","type":"internal"},{"Timestamp":"2023-03-02T23:40:41.631748724Z","duration_ms":1.44271,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":39108,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"cf1940eaa36baee6","trace.trace_id":"62032b8bcdc8dbbc66efa93c42e9a80d","type":"server"},{"Timestamp":"2023-03-02T23:40:38.215743909Z","duration_ms":1.07928,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.scheme":"http","http.server_name":"0.0.0.0","http.status_code":404,"http.target":"/?vscodeBrowserReqId=1677800438089","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"HTTP GET","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":57794,"service.name":"backend-flask","span.kind":"server","span.num_events":0,"span.num_links":0,"status_code":0,"telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"fe98ff0ffd25dece","trace.trace_id":"16c1fa49d631e2cba991c7d14f1d4bb2","type":"server"},{"Timestamp":"2023-03-02T23:40:34.409695484Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"c2f246a28ab8b1d4","trace.trace_id":"38a346fdd423b1455c982b5c920875c8"},{"Timestamp":"2023-03-02T23:40:34.408693484Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"63c386d2c58398a4","trace.trace_id":"38a346fdd423b1455c982b5c920875c8"},{"Timestamp":"2023-03-02T23:40:34.408132264Z","duration_ms":0.58262,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"c2f246a28ab8b1d4","trace.span_id":"63c386d2c58398a4","trace.trace_id":"38a346fdd423b1455c982b5c920875c8","type":"internal"},{"Timestamp":"2023-03-02T23:40:34.403788775Z","duration_ms":5.9201,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":57758,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"c2f246a28ab8b1d4","trace.trace_id":"38a346fdd423b1455c982b5c920875c8","type":"server"},{"Timestamp":"2023-03-02T23:39:50.91652561Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"6b779b25fdbf972b","trace.trace_id":"e0cd50335bb10864b8e2e7b50ca56c2c"},{"Timestamp":"2023-03-02T23:39:50.91604964Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"778a5161c8a8b9e8","trace.trace_id":"e0cd50335bb10864b8e2e7b50ca56c2c"},{"Timestamp":"2023-03-02T23:39:50.91585592Z","duration_ms":0.21008,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"6b779b25fdbf972b","trace.span_id":"778a5161c8a8b9e8","trace.trace_id":"e0cd50335bb10864b8e2e7b50ca56c2c","type":"internal"},{"Timestamp":"2023-03-02T23:39:50.91521721Z","duration_ms":1.3196,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":37396,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"6b779b25fdbf972b","trace.trace_id":"e0cd50335bb10864b8e2e7b50ca56c2c","type":"server"},{"Timestamp":"2023-03-02T23:39:50.33112773Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"82a9026f3ffca29e","trace.trace_id":"f3b92eb0850979d82dc1feaab7dab4af"},{"Timestamp":"2023-03-02T23:39:50.3300657Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 12, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"49c9a1d3aa84a159","trace.trace_id":"f3b92eb0850979d82dc1feaab7dab4af"},{"Timestamp":"2023-03-02T23:39:50.32950731Z","duration_ms":0.58224,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"82a9026f3ffca29e","trace.span_id":"49c9a1d3aa84a159","trace.trace_id":"f3b92eb0850979d82dc1feaab7dab4af","type":"internal"},{"Timestamp":"2023-03-02T23:39:50.32548044Z","duration_ms":5.66103,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":37348,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"82a9026f3ffca29e","trace.trace_id":"f3b92eb0850979d82dc1feaab7dab4af","type":"server"},{"Timestamp":"2023-03-02T23:39:03.61068972Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 14, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"1ea7dc8d866bed94","trace.trace_id":"7dd729e1d9879c9942e4bfd190a0a355"},{"Timestamp":"2023-03-02T23:39:03.610085029Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 14, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"946f22d92f041662","trace.trace_id":"7dd729e1d9879c9942e4bfd190a0a355"},{"Timestamp":"2023-03-02T23:39:03.609900489Z","duration_ms":0.202491,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"1ea7dc8d866bed94","trace.span_id":"946f22d92f041662","trace.trace_id":"7dd729e1d9879c9942e4bfd190a0a355","type":"internal"},{"Timestamp":"2023-03-02T23:39:03.60922062Z","duration_ms":1.484869,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":57314,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"1ea7dc8d866bed94","trace.trace_id":"7dd729e1d9879c9942e4bfd190a0a355","type":"server"},{"Timestamp":"2023-03-02T23:38:57.75913677Z","duration_ms":1.09181,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.scheme":"http","http.server_name":"0.0.0.0","http.status_code":404,"http.target":"/","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"HTTP GET","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":54958,"service.name":"backend-flask","span.kind":"server","span.num_events":0,"span.num_links":0,"status_code":0,"telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"877bd84a74f2f964","trace.trace_id":"9aa23a31f5891a9f574caa9117a41abb","type":"server"},{"Timestamp":"2023-03-02T23:38:45.825609583Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 14, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"8069d944afbd666c","trace.trace_id":"eaa394294c02b603816a84551e1b0a65"},{"Timestamp":"2023-03-02T23:38:45.824990094Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 14, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"0e32e558e545d619","trace.trace_id":"eaa394294c02b603816a84551e1b0a65"},{"Timestamp":"2023-03-02T23:38:45.824764503Z","duration_ms":0.242951,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"8069d944afbd666c","trace.span_id":"0e32e558e545d619","trace.trace_id":"eaa394294c02b603816a84551e1b0a65","type":"internal"},{"Timestamp":"2023-03-02T23:38:45.824071314Z","duration_ms":1.54972,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":56886,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"8069d944afbd666c","trace.trace_id":"eaa394294c02b603816a84551e1b0a65","type":"server"},{"Timestamp":"2023-03-02T23:38:45.083795212Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 14, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"ea77cc3e6da97df8","trace.trace_id":"c3ce0c4d061cf10535b74f2dbd660710"},{"Timestamp":"2023-03-02T23:38:45.083224332Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 14, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"d2261ae89fba8081","trace.trace_id":"c3ce0c4d061cf10535b74f2dbd660710"},{"Timestamp":"2023-03-02T23:38:45.082910021Z","duration_ms":0.332751,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"ea77cc3e6da97df8","trace.span_id":"d2261ae89fba8081","trace.trace_id":"c3ce0c4d061cf10535b74f2dbd660710","type":"internal"},{"Timestamp":"2023-03-02T23:38:45.082149792Z","duration_ms":1.65922,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":56842,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"ea77cc3e6da97df8","trace.trace_id":"c3ce0c4d061cf10535b74f2dbd660710","type":"server"},{"Timestamp":"2023-03-02T23:38:39.053615082Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2531, in wsgi_app\n    response = self.handle_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 2528, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1825, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python3.10/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/backend-flask/app.py\", line 95, in data_home\n    data = HomeActivities.run()\n  File \"/backend-flask/services/home_activities.py\", line 14, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"/api/activities/home","service.name":"backend-flask","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"8393a69a09aeef9c","trace.trace_id":"b20264c92ac695e41e81fc6908c37894"},{"Timestamp":"2023-03-02T23:38:39.052552162Z","error":true,"exception.escaped":"False","exception.message":"'str' object is not callable","exception.stacktrace":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 573, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py\", line 1045, in start_as_current_span\n    yield span_context\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 440, in start_as_current_span\n    yield span\n  File \"/backend-flask/services/home_activities.py\", line 14, in run\n    span.set_attribute(\"app.now\", now.isoformat()())\nTypeError: 'str' object is not callable\n","exception.type":"TypeError","library.name":"home.activities","meta.annotation_type":"span_event","meta.signal_type":"trace","name":"exception","parent_name":"home-activities-mock-data","service.name":"backend-flask","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"340ab500e29de47c","trace.trace_id":"b20264c92ac695e41e81fc6908c37894"},{"Timestamp":"2023-03-02T23:38:39.051991272Z","duration_ms":0.58149,"error":true,"library.name":"home.activities","meta.signal_type":"trace","name":"home-activities-mock-data","service.name":"backend-flask","span.kind":"internal","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.parent_id":"8393a69a09aeef9c","trace.span_id":"340ab500e29de47c","trace.trace_id":"b20264c92ac695e41e81fc6908c37894","type":"internal"},{"Timestamp":"2023-03-02T23:38:39.047554952Z","duration_ms":6.07398,"error":true,"http.flavor":"1.1","http.host":"4567-yaya2devops-awscloudpro-ccot7vfi3ph.ws-eu89.gitpod.io","http.method":"GET","http.route":"/api/activities/home","http.scheme":"http","http.server_name":"0.0.0.0","http.target":"/api/activities/home","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","library.name":"opentelemetry.instrumentation.flask","library.version":"0.37b0","meta.signal_type":"trace","name":"/api/activities/home","net.host.port":4567,"net.peer.ip":"192.168.32.140","net.peer.port":40238,"service.name":"backend-flask","span.kind":"server","span.num_events":1,"span.num_links":0,"status_code":2,"status_message":"TypeError: 'str' object is not callable","telemetry.instrumentation_library":true,"telemetry.sdk.language":"python","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.16.0","trace.span_id":"8393a69a09aeef9c","trace.trace_id":"b20264c92ac695e41e81fc6908c37894","type":"server"}]
